name: Deploy Node.js to Heroku

on:
  push:
    branches:
      - main  # run only when pushing to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone repository
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📂 Install dependencies
        run: npm install

      - name: ✅ Run tests
        run: npm test

      - name: 🚀 Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
